### PR TITLE
Add CRUD for Clojure

### PR DESCRIPTION
**Pull request by tbsschroeder**

### CODE REVIEW

**Comment by blueseaturtle** [comment]
Thanks for your contribution!
But is this PR still a draft? Because the committed file seems to be a nested git repository and therefore doesn't seem to have content when cloned.

**Comment by tbsschroeder** [comment]
Yes, I was on a wrong/local branch, will fix it this week :)

**Comment by blueseaturtle** [comment]
Sure, thanks!
And a small README file to the root of your project folder describing what the project does, and how it can be run locally, would be very helpful. [Example](https://github.com/blueseaturtle/The-CRUD-Collection/tree/main/React_Redis/RhymePingPong#how-to-run-it-locally)

**Comment by tbsschroeder** [comment]
I'll close this one and open a new one for a smoother review.

**Pull request closed without merging**
